a=input("enter your num :") # input always come to string if we wants to give int string than a=int(input())
b=input("enter your num :")
print("your answer " ,int(a) - int(b))
print("your answer " ,int(a) + int(b))
print("your answer " ,int(a) * int(b))
print("your answer " ,float(a) / float(b))
